---
- name: restart cadvisor
  command: docker compose -p cadvisor -f {{ cadvisor_base_dir }}/docker-compose.yml restart
  args:
    chdir: "{{ cadvisor_base_dir }}"
  when: not ansible_check_mode

- name: stop cadvisor
  command: docker compose -p cadvisor -f {{ cadvisor_base_dir }}/docker-compose.yml down
  args:
    chdir: "{{ cadvisor_base_dir }}"
  when: not ansible_check_mode

- name: start cadvisor
  command: docker compose -p cadvisor -f {{ cadvisor_base_dir }}/docker-compose.yml up -d
  args:
    chdir: "{{ cadvisor_base_dir }}"
  when: not ansible_check_mode
