---
# Node Exporter role variables for native installation

# Node Exporter version and download URLs
node_exporter_version: "1.6.1"
node_exporter_binary_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_checksums_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/sha256sums.txt"

# Installation directories
node_exporter_install_dir: "/usr/local/bin"
node_exporter_config_dir: "/etc/node_exporter"
node_exporter_data_dir: "/var/lib/node_exporter"
node_exporter_log_dir: "/var/log/node_exporter"

# System user and group
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_shell: "/bin/false"
node_exporter_home: "/var/lib/node_exporter"

# Service configuration
node_exporter_port: 9100
node_exporter_web_listen_address: "0.0.0.0:9100"
node_exporter_web_telemetry_path: "/metrics"
node_exporter_web_disable_exporter_metrics: false
node_exporter_web_max_requests: 40

# Log configuration
node_exporter_log_level: "info"
node_exporter_log_format: "logfmt"

# Collectors configuration - enabled by default
node_exporter_enabled_collectors:
  - arp
  - bcache
  - conntrack
  - cpu
  - cpufreq
  - diskstats
  - edac
  - entropy
  - filefd
  - filesystem
  - hwmon
  - infiniband
  - loadavg
  - mdadm
  - meminfo
  - netdev
  - netstat
  - sockstat
  - stat
  - textfile
  - time
  - timex
  - uname
  - vmstat
  - xfs
  - zfs

# Collectors to disable
node_exporter_disabled_collectors: []

# Filesystem collector configuration
node_exporter_filesystem_ignored_mount_points: "^/(dev|proc|sys|var/lib/docker/.+)($|/)"
node_exporter_filesystem_ignored_fs_types: "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$"

# Network collector configuration
node_exporter_netdev_device_blacklist: "^(veth.*|docker.*|br-.*|lo)$"
node_exporter_netstat_fields: "^(.*_(InErrors|InErrs)|Ip_Forwarding|Ip(6|Ext)_(InOctets|OutOctets)|Icmp6?_(InMsgs|OutMsgs)|TcpExt_(Listen.*|Syncookies.*|TCPSynRetrans)|Tcp_(ActiveOpens|PassiveOpens|RetransSegs|CurrEstab)|Udp6?_(InDatagrams|OutDatagrams|NoPorts|RcvbufErrors|SndbufErrors))$"

# Textfile collector configuration
node_exporter_textfile_directory: "/var/lib/node_exporter/textfile_collector"

# CPU collector configuration
node_exporter_cpu_info: true

# SystemD collector configuration
node_exporter_systemd_enable: true
node_exporter_systemd_enable_task_metrics: false
node_exporter_systemd_enable_restarts_metrics: false
node_exporter_systemd_enable_start_time_metrics: false

# Hardware monitoring
node_exporter_hwmon_chip_blacklist: ""

# NTP configuration
node_exporter_ntp_server: ""
node_exporter_ntp_protocol_version: 4
node_exporter_ntp_server_is_local: false
node_exporter_ntp_ip_ttl: 1

# Supervisord configuration
node_exporter_supervisord_url: "http://localhost:9001/RPC2"

# Perf configuration
node_exporter_perf_cpus: ""
node_exporter_perf_tracepoint: ""

# Powersupply configuration
node_exporter_powersupply_ignored_supplies: "^$"

# runit configuration
node_exporter_runit_servicedir: "/etc/service"

# Thermal zone configuration
node_exporter_thermal_zone_device_blacklist: ""

# Additional command line arguments
node_exporter_additional_args: []

# Service management
node_exporter_service_enabled: true
node_exporter_service_state: "started"

# Firewall configuration
node_exporter_firewall_enabled: true
node_exporter_firewall_zone: "public"

# Archive extraction temporary directory
node_exporter_temp_dir: "/tmp"

# Systemd service configuration
node_exporter_systemd_after: "network.target"
node_exporter_systemd_wants: "network.target"
node_exporter_systemd_restart: "on-failure"
node_exporter_systemd_restart_sec: "5"

# Process limits
node_exporter_limit_nofile: 65536
node_exporter_limit_nproc: 65536

# Security settings
node_exporter_no_new_privileges: true
node_exporter_protect_home: true
node_exporter_protect_system: "strict"
node_exporter_private_tmp: true
