---
# Node Exporter role variables

# Base directory for Node Exporter
node_exporter_base_dir: "/opt/monitoring/node-exporter"

# Node Exporter service configuration
node_exporter_port: 9100
node_exporter_image: "prom/node-exporter:latest"

# Node Exporter user (runs as nobody)
node_exporter_user: "nobody"

# Collectors to enable (default: all enabled)
node_exporter_enabled_collectors:
  - arp
  - bcache
  - bonding
  - conntrack
  - cpu
  - cpufreq
  - diskstats
  - edac
  - entropy
  - filefd
  - filesystem
  - hwmon
  - infiniband
  - ipvs
  - loadavg
  - mdadm
  - meminfo
  - netclass
  - netdev
  - netstat
  - nfs
  - nfsd
  - nvme
  - os
  - pressure
  - rapl
  - schedstat
  - sockstat
  - softnet
  - stat
  - textfile
  - thermal_zone
  - time
  - timex
  - udp_queues
  - uname
  - vmstat
  - xfs
  - zfs

# Collectors to disable
node_exporter_disabled_collectors: []

# Filesystem mount points to exclude
node_exporter_filesystem_mount_points_exclude: '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'

# Filesystem types to exclude
node_exporter_filesystem_fs_types_exclude: '^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$'

# Network device exclude pattern
node_exporter_netdev_device_exclude: ''

# Netclass device exclude pattern
node_exporter_netclass_ignored_devices: '^(veth.*|cali.*|[a-f0-9]{15})$'

# Path configurations for host filesystem access
node_exporter_path_procfs: "/host/proc"
node_exporter_path_sysfs: "/host/sys"
node_exporter_path_rootfs: "/rootfs"

# Textfile collector directory
node_exporter_textfile_directory: "/node_exporter/textfile_collector"

# Web configuration
node_exporter_web_listen_address: ":9100"
node_exporter_web_telemetry_path: "/metrics"
node_exporter_web_disable_exporter_metrics: false
node_exporter_web_max_requests: 40

# TLS configuration
node_exporter_tls_enabled: false
node_exporter_tls_cert_file: ""
node_exporter_tls_key_file: ""

# Basic auth configuration
node_exporter_basic_auth_enabled: false
node_exporter_basic_auth_users: {}
# Example:
# node_exporter_basic_auth_users:
#   prometheus: "$2b$12$hashed_password_here"

# Log configuration
node_exporter_log_level: "info"
node_exporter_log_format: "logfmt"

# Network settings
node_exporter_network_name: "monitoring"
node_exporter_network_external: true

# Docker specific settings
node_exporter_container_name: "node-exporter"
node_exporter_restart_policy: "unless-stopped"
node_exporter_privileged: true
node_exporter_pid_mode: "host"

# Security options
node_exporter_security_opt:
  - "apparmor:unconfined"

# Additional volumes for specific collectors
node_exporter_additional_volumes: []
# Example:
# node_exporter_additional_volumes:
#   - "/custom/path:/custom/path:ro"

# Environment variables
node_exporter_env_vars: {}

# Health check settings
node_exporter_healthcheck_interval: "30s"
node_exporter_healthcheck_timeout: "5s"
node_exporter_healthcheck_retries: 3
node_exporter_healthcheck_start_period: "10s"

# Labels to add to exported metrics
node_exporter_const_labels: {}
# Example:
# node_exporter_const_labels:
#   environment: "production"
#   datacenter: "us-east-1"
