---
- name: Install monitoring backup script
  template:
    src: backup-monitoring.sh.j2
    dest: "{{ monitoring_base_dir }}/scripts/backup-monitoring.sh"
    owner: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
    group: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
    mode: "0755"
  when: monitoring_enable_backup

- name: Install monitoring helper scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ monitoring_scripts_dir }}/{{ item }}"
    owner: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
    group: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
    mode: "0755"
  loop:
    - check-services.sh

- name: Create monitoring service status script
  template:
    src: service-status.sh.j2
    dest: "{{ monitoring_scripts_dir }}/service-status.sh"
    owner: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
    group: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
    mode: "0755"
