global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "monitoring-system"
    prometheus_replica: "prometheus-01"

rule_files:
  - "/etc/prometheus/alert-rules.yml"
  - "/etc/prometheus/alloy-rules.yml"
  - "/etc/prometheus/recording-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
      timeout: 10s
      api_version: v2

# Remote write configuration for federation or long-term storage
remote_write:
  - url: "http://localhost:9090/api/v1/write"
    name: "local-prometheus"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: "up|prometheus_.*|alloy_.*|node_.*|container_.*|go_.*"
        action: keep
    queue_config:
      capacity: 10000
      max_samples_per_send: 2000
      batch_send_deadline: 5s
      min_shards: 1
      max_shards: 50
      max_retries: 5
      min_backoff: 30ms
      max_backoff: 5s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true

  # Grafana Alloy - Primary metrics collection agent
  - job_name: "alloy"
    static_configs:
      - targets:
          - "192.168.122.31:12345"
          - "192.168.122.94:12345"
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    honor_timestamps: true
    relabel_configs:
      # Extract instance name from address
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: instance
        replacement: "$1"
      # Add alloy-specific labels
      - target_label: job
        replacement: "alloy"
      - target_label: service
        replacement: "grafana-alloy"
    metric_relabel_configs:
      # Keep important Alloy internal metrics
      - source_labels: [__name__]
        regex: "alloy_.*|prometheus_.*|loki_.*|up|scrape_.*"
        action: keep
      # Rename some metrics for consistency
      - source_labels: [__name__]
        regex: "alloy_build_info"
        target_label: __name__
        replacement: "alloy_up"

  # System metrics via Alloy (replaces node_exporter)
  - job_name: "node-metrics-via-alloy"
    static_configs:
      - targets:
          - "192.168.122.31:12345"
          - "192.168.122.94:12345"
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    honor_labels: true
    params:
      collector: ["node"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: instance
        replacement: "$1"
      - target_label: job
        replacement: "node"
    metric_relabel_configs:
      # Keep only node_* metrics from Alloy
      - source_labels: [__name__]
        regex: "node_.*"
        action: keep
      # Drop high cardinality metrics
      - source_labels: [__name__]
        regex: "node_filesystem_.*"
        source_labels: [fstype]
        regex: "tmpfs|devtmpfs|overlay|squashfs|proc|sysfs|cgroup.*"
        action: drop

  # Container metrics via cAdvisor (if enabled in Alloy)
  - job_name: "cadvisor-via-alloy"
    static_configs:
      - targets:
          - "192.168.122.31:12345"
          - "192.168.122.94:12345"
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /metrics
    honor_labels: true
    params:
      collector: ["cadvisor"]
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: instance
        replacement: "$1"
      - target_label: job
        replacement: "cadvisor"
    metric_relabel_configs:
      # Keep only container_* metrics
      - source_labels: [__name__]
        regex: "container_.*"
        action: keep
      # Drop pause containers and system containers
      - source_labels: [container_label_io_kubernetes_pod_name]
        regex: ".*pause.*"
        action: drop
      - source_labels: [name]
        regex: "k8s_POD_.*"
        action: drop

  # Legacy cAdvisor direct scraping (fallback)
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "container_.*"
        action: keep
      - source_labels: [name]
        regex: "^$"
        action: drop

  # Alertmanager monitoring
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Grafana monitoring
  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /metrics

  # Loki monitoring
  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /metrics

  # Alloy health check endpoints
  - job_name: "alloy-health"
    static_configs:
      - targets:
          - "192.168.122.31:12345"
          - "192.168.122.94:12345"
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /-/ready
    relabel_configs:
      - source_labels: [__address__]
        regex: "([^:]+):.*"
        target_label: instance
        replacement: "$1"
      - target_label: job
        replacement: "alloy-health"

  # Service Discovery for dynamic Alloy instances (if using)
  - job_name: "alloy-discovery"
    file_sd_configs:
      - files:
          - "/etc/prometheus/sd/alloy-*.yml"
        refresh_interval: 30s
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__meta_alloy_role]
        target_label: alloy_role
      - source_labels: [__meta_alloy_datacenter]
        target_label: datacenter
      - source_labels: [__meta_alloy_environment]
        target_label: environment

# Storage configuration optimized for Alloy metrics
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 30d
    retention.size: 50GB
    min-block-duration: 2h
    max-block-duration: 25h
    wal-compression: true
    no-lockfile: false
    head-chunks-write-queue-size: 10000

# Optional: Federation for multi-cluster setup
# federation:
#   - job_name: 'federate'
#     scrape_interval: 15s
#     honor_labels: true
#     metrics_path: '/federate'
#     params:
#       match[]:
#         - '{job="alloy"}'
#         - '{job="node"}'
#         - '{__name__=~"up|alloy_.*|node_.*"}'
#     static_configs:
#       - targets:
#         - 'remote-prometheus:9090'
