---
# Prometheus role variables

# Base directory for Prometheus
prometheus_base_dir: "/opt/monitoring/prometheus"

# Prometheus service configuration
prometheus_port: 9090
prometheus_image: "prom/prometheus:v2.45.0"

# Prometheus user/group IDs (matching the official image)
prometheus_user_id: "65534"
prometheus_group_id: "65534"

# Prometheus configuration
prometheus_retention: "30d"
prometheus_scrape_interval: "15s"
prometheus_evaluation_interval: "15s"

# Storage settings
prometheus_storage_size: "10GB"

# Alert rules
prometheus_alert_rules_enabled: true
enable_default_alerts: true
custom_alert_rules: []

# Alertmanager integration
alertmanager_url: "http://alertmanager:9093"

# Scrape configs
prometheus_scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

# Additional scrape targets
additional_scrape_targets: []

# Network settings
prometheus_network_name: "monitoring"
prometheus_network_external: true

# Command line flags
prometheus_extra_args:
  - "--web.enable-lifecycle"
  - "--web.enable-admin-api"
  - "--storage.tsdb.wal-compression"

# Labels to add to all metrics
prometheus_external_labels: {}
