---
- name: Create Promtail directories
  file:
    path: "{{ promtail_base_dir }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - configs
    - positions

- name: Copy Promtail configuration
  template:
    src: promtail-config.yml.j2
    dest: "{{ promtail_base_dir }}/configs/promtail-config.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: restart promtail

- name: Copy Docker Compose file for Promtail
  template:
    src: docker-compose.yml.j2
    dest: "{{ promtail_base_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  notify: restart promtail

- name: Check if Promtail is already running
  command: docker ps -q --filter name=promtail
  register: promtail_status
  changed_when: false
  failed_when: false
  when: not ansible_check_mode

- name: Start Promtail
  command: docker compose -p promtail -f {{ promtail_base_dir }}/docker-compose.yml up -d
  args:
    chdir: "{{ promtail_base_dir }}"
  when:
    - not ansible_check_mode
    - promtail_status is defined
    - promtail_status.stdout == ""

- name: Wait for Promtail to be ready
  wait_for:
    port: "{{ promtail_port }}"
    host: localhost
    delay: 5
    timeout: 60
  when: not ansible_check_mode

- name: Verify Promtail is running
  uri:
    url: "http://localhost:{{ promtail_port }}/ready"
    method: GET
    status_code: 200
    timeout: 30
  register: promtail_health
  retries: 3
  delay: 5
  when: not ansible_check_mode

- name: Check Promtail metrics
  uri:
    url: "http://localhost:{{ promtail_port }}/metrics"
    method: GET
    status_code: 200
  register: promtail_metrics
  failed_when: false

- name: Verify Promtail is pushing logs
  assert:
    that:
      - "'promtail_sent_entries_total' in promtail_metrics.content"
      - "'promtail_read_lines_total' in promtail_metrics.content"
    fail_msg: "Promtail metrics indicate it may not be collecting logs properly"
    success_msg: "Promtail is collecting and forwarding logs successfully"
  when: promtail_metrics is defined and promtail_metrics.content is defined

- name: Display Promtail information
  debug:
    msg: |
      Promtail deployed successfully!

      Service is available at:
      - Promtail API: http://{{ ansible_default_ipv4.address }}:{{ promtail_port }}
      - Metrics endpoint: http://{{ ansible_default_ipv4.address }}:{{ promtail_port }}/metrics
      - Ready endpoint: http://{{ ansible_default_ipv4.address }}:{{ promtail_port }}/ready

      Promtail is configured to:
      - Collect logs from: {{ promtail_log_paths | join(', ') }}
      - Send logs to Loki at: {{ promtail_loki_url }}

      Log positions are stored in: {{ promtail_base_dir }}/positions

      To view Promtail targets and their status:
      - http://{{ ansible_default_ipv4.address }}:{{ promtail_port }}/targets
