---
- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: reload docker
  systemd:
    name: docker
    state: reloaded