---
- name: Deploy Monitoring Stack with Individual Roles
  hosts: monitoring_servers
  become: true
  gather_facts: true

  vars:
    # Override default variables as needed
    monitoring_base_dir: /opt/monitoring
    monitoring_network_name: monitoring

    # Component-specific overrides
    prometheus_retention: "30d"
    grafana_admin_password: "admin123"
    loki_retention_period: "744h"

  pre_tasks:
    - name: Ensure system is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    # Deploy common prerequisites first
    - role: monitoring-common
      tags: [common, always]

    # Deploy core monitoring components
    - role: prometheus
      tags: [prometheus, metrics]
      vars:
        prometheus_scrape_configs:
          - job_name: "prometheus"
            static_configs:
              - targets: ["localhost:9090"]
          - job_name: "cadvisor"
            static_configs:
              - targets: ["cadvisor:8080"]

    - role: alertmanager
      tags: [alertmanager, alerts]
      vars:
        alertmanager_receivers:
          - name: "default"
            email_configs: []
            slack_configs: []
            webhook_configs: []

    - role: loki
      tags: [loki, logs]

    - role: grafana
      tags: [grafana, visualization]
      vars:
        grafana_datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: "http://prometheus:9090"
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: "http://loki:3100"

    # Note: Exporters are now deployed via separate playbooks
    # Run deploy-node-exporter.yml and deploy-cadvisor.yml separately

  post_tasks:
    - name: Wait for all services to stabilize
      pause:
        seconds: 30

    - name: Run service health check
      command: "{{ monitoring_base_dir }}/scripts/check-services.sh"
      register: health_check
      failed_when: health_check.rc != 0
      changed_when: false

    - name: Display health check results
      debug:
        var: health_check.stdout_lines

    - name: Create monitoring summary file
      template:
        src: monitoring-summary.txt.j2
        dest: "{{ monitoring_base_dir }}/MONITORING_SUMMARY.txt"
        mode: "0644"
      vars:
        deployment_date: "{{ ansible_date_time.iso8601 }}"

    - name: Display access information
      debug:
        msg: |
          ============================================
          Monitoring Stack Deployment Complete!
          ============================================

          Access URLs:
          - Prometheus: http://{{ ansible_default_ipv4.address }}:9090
          - Grafana: http://{{ ansible_default_ipv4.address }}:3000
            Username: admin
            Password: {{ grafana_admin_password }}
          - Loki: http://{{ ansible_default_ipv4.address }}:3100
          - Alertmanager: http://{{ ansible_default_ipv4.address }}:9093
          Note: Exporters are deployed separately for better modularity
          To deploy Node Exporter: ansible-playbook playbooks/deploy-node-exporter.yml
          To deploy cAdvisor: ansible-playbook playbooks/deploy-cadvisor.yml
          To deploy Promtail: ansible-playbook playbooks/deploy-promtail.yml

          Configuration files: {{ monitoring_base_dir }}

          To check service status:
          {{ monitoring_base_dir }}/scripts/check-services.sh

          To view logs:
          {{ monitoring_base_dir }}/scripts/view-logs.sh

          ============================================

- name: Configure Monitoring Components
  hosts: monitoring_servers
  become: true
  gather_facts: false
  tags: [configure, never]

  tasks:
    - name: Configure Prometheus scrape targets
      lineinfile:
        path: "{{ monitoring_base_dir }}/prometheus/configs/prometheus.yml"
        line: "      - targets: ['{{ item }}']"
        insertafter: "    static_configs:"
        state: present
      loop:
        - "app-server-1:8080"
        - "app-server-2:8080"
      notify: reload prometheus
      tags: [prometheus-config]

    - name: Import Grafana dashboards
      uri:
        url: "http://localhost:3000/api/dashboards/db"
        method: POST
        user: admin
        password: "{{ grafana_admin_password }}"
        force_basic_auth: yes
        body_format: json
        body:
          dashboard:
            title: "Custom Application Dashboard"
            panels: []
          overwrite: true
      tags: [grafana-config]

    - name: Configure Alertmanager receivers
      template:
        src: custom-receivers.yml.j2
        dest: "{{ monitoring_base_dir }}/alertmanager/configs/receivers.yml"
      notify: restart alertmanager
      tags: [alertmanager-config]

  handlers:
    - name: reload prometheus
      uri:
        url: "http://localhost:9090/-/reload"
        method: POST

    - name: restart alertmanager
      command: docker restart alertmanager

# Playbook for selective component deployment
- name: Deploy Specific Monitoring Components
  hosts: monitoring_servers
  become: true
  gather_facts: true
  tags: [selective, never]

  vars:
    deploy_prometheus: "{{ prometheus | default(false) }}"
    deploy_grafana: "{{ grafana | default(false) }}"
    deploy_loki: "{{ loki | default(false) }}"
    deploy_alertmanager: "{{ alertmanager | default(false) }}"
    deploy_exporters: "{{ exporters | default(false) }}"
    deploy_promtail: "{{ promtail | default(false) }}"

  tasks:
    - name: Deploy Prometheus only
      include_role:
        name: prometheus
      when: deploy_prometheus

    - name: Deploy Grafana only
      include_role:
        name: grafana
      when: deploy_grafana

    - name: Deploy Loki only
      include_role:
        name: loki
      when: deploy_loki

    - name: Deploy Alertmanager only
      include_role:
        name: alertmanager
      when: deploy_alertmanager

    - name: Deploy exporters only
      debug:
        msg: "Exporters are now deployed via separate playbooks. Use deploy-node-exporter.yml and deploy-cadvisor.yml"
      when: deploy_exporters

    - name: Note about Promtail deployment
      debug:
        msg: "Promtail should be deployed on client hosts using deploy-promtail.yml playbook"
      when: deploy_promtail
# Update monitoring stack playbook
- name: Update Monitoring Stack Components
  hosts: monitoring_servers
  become: true
  gather_facts: false
  tags: [update, never]

  tasks:
    - name: Pull latest images
      docker_image:
        name: "{{ item }}"
        source: pull
        force_source: yes
      loop:
        - "{{ prometheus_image | default('prom/prometheus:latest') }}"
        - "{{ grafana_image | default('grafana/grafana:latest') }}"
        - "{{ loki_image | default('grafana/loki:latest') }}"
        - "{{ alertmanager_image | default('prom/alertmanager:latest') }}"
        - "{{ cadvisor_image | default('gcr.io/cadvisor/cadvisor:latest') }}"

    - name: Restart monitoring services
      shell: |
        cd {{ monitoring_base_dir }}/{{ item }}
        docker compose down
        docker compose up -d
      loop:
        - prometheus
        - grafana
        - loki
        - alertmanager
        - cadvisor

# Backup monitoring data playbook
- name: Backup Monitoring Stack Data
  hosts: monitoring_servers
  become: true
  gather_facts: false
  tags: [backup, never]

  tasks:
    - name: Run backup script
      command: "{{ monitoring_base_dir }}/backup-monitoring.sh"
      register: backup_result

    - name: Display backup result
      debug:
        var: backup_result.stdout_lines

    - name: Copy backup to remote location
      synchronize:
        src: "{{ monitoring_base_dir }}/backups/"
        dest: "{{ backup_remote_path }}/"
        mode: push
      when: backup_remote_path is defined
# Usage examples:
# Deploy core monitoring stack:
# ansible-playbook -i inventory deploy-monitoring-individual.yml
#
# Deploy with specific tags:
# ansible-playbook -i inventory deploy-monitoring-individual.yml --tags prometheus,grafana
#
# Configure components after deployment:
# ansible-playbook -i inventory deploy-monitoring-individual.yml --tags configure
#
# Deploy specific components only:
# ansible-playbook -i inventory deploy-monitoring-individual.yml --tags selective -e prometheus=true -e grafana=true
#
# Update components:
# ansible-playbook -i inventory deploy-monitoring-individual.yml --tags update
#
# Backup data:
# ansible-playbook -i inventory deploy-monitoring-individual.yml --tags backup
#
# Deploy exporters separately:
# ansible-playbook -i inventory playbooks/deploy-node-exporter.yml
# ansible-playbook -i inventory playbooks/deploy-cadvisor.yml
#
# Deploy Promtail on client hosts:
# ansible-playbook -i inventory playbooks/deploy-promtail.yml
