---
- name: Install Docker on Debian 12 servers
  hosts: monitoring_servers
  become: true
  gather_facts: true

  pre_tasks:
    - name: Verify OS is Debian 12
      fail:
        msg: "This playbook is designed for Debian 12 only. Current OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      when: >
        ansible_distribution != "Debian" or
        ansible_distribution_major_version != "12"

    - name: Update system packages
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        autoclean: yes
      when: update_system | default(false) | bool

  roles:
    - docker

  post_tasks:
    - name: Test Docker installation
      command: docker run --rm hello-world
      register: docker_test
      changed_when: false

    - name: Display Docker test results
      debug:
        msg: "Docker test completed successfully"
      when: docker_test.rc == 0

    - name: Test Docker Compose
      command: docker compose version
      register: compose_test
      changed_when: false

    - name: Display Docker Compose version
      debug:
        msg: "Docker Compose version: {{ compose_test.stdout }}"
      when: compose_test.rc == 0

  vars:
    # Set to true if you want to update all system packages
    update_system: false

    # Users to add to docker group (in addition to ansible_user)
    docker_users:
      - "{{ ansible_user }}"
      # Add more users as needed
      # - user1
      # - user2
