---
# Common monitoring variables shared across all monitoring roles
# Updated for native service installations (no Docker dependencies)

# Docker control (set to false for native installations)
monitoring_docker_enabled: false

# Base directory for all monitoring services
monitoring_base_dir: "/opt/monitoring"

# Common user for monitoring services
monitoring_user: "monitoring"
monitoring_create_user: true

# Domain configuration
monitoring_domain: "{{ ansible_default_ipv4.address }}"

# SSL/TLS configuration
monitoring_ssl_enabled: false
monitoring_ssl_self_signed: true
monitoring_ssl_dir: "{{ monitoring_base_dir }}/ssl"
monitoring_ssl_cert_file: "{{ monitoring_ssl_dir }}/monitoring.crt"
monitoring_ssl_key_file: "{{ monitoring_ssl_dir }}/monitoring.key"

# Backup configuration
monitoring_enable_backup: true
monitoring_backup_dir: "{{ monitoring_base_dir }}/backups"
monitoring_backup_retention_days: 7
monitoring_backup_hour: "2"
monitoring_backup_minute: "0"

# Log rotation
monitoring_enable_logrotate: true
monitoring_log_retention_days: 30
monitoring_log_max_size: "100M"

# Scripts directory
monitoring_scripts_dir: "{{ monitoring_base_dir }}/scripts"

# Default resource limits
monitoring_default_memory_limit: "512M"
monitoring_default_cpu_limit: "1.0"

# Common labels for all services
monitoring_common_labels:
  environment: "{{ environment | default('production') }}"
  managed_by: "ansible"
  stack: "monitoring"

# Service discovery
monitoring_enable_service_discovery: true
monitoring_consul_endpoint: ""
monitoring_etcd_endpoint: ""

# High availability settings
monitoring_ha_enabled: false
monitoring_ha_replicas: 2

# Storage settings
monitoring_storage_driver: "local"
monitoring_storage_path: "{{ monitoring_base_dir }}/data"

# Performance tuning
monitoring_enable_performance_tuning: true
monitoring_max_open_files: 65536
monitoring_max_processes: 32768

# Security settings
monitoring_enable_basic_auth: false
monitoring_enable_oauth: false
monitoring_oauth_provider: ""
monitoring_oauth_client_id: ""
monitoring_oauth_client_secret: ""

# SystemD security hardening
monitoring_enable_systemd_hardening: true

# Notification settings
monitoring_notification_email: ""
monitoring_notification_slack_webhook: ""
monitoring_notification_pagerduty_key: ""

# Update settings
monitoring_auto_update: false
monitoring_update_schedule: "0 4 * * 0" # Weekly on Sunday at 4 AM

# Proxy settings
monitoring_http_proxy: ""
monitoring_https_proxy: ""
monitoring_no_proxy: "localhost,127.0.0.1"

# DNS settings
monitoring_dns_servers: []
monitoring_search_domains: []

# Time zone
monitoring_timezone: "UTC"

# Debugging
monitoring_debug_enabled: false
monitoring_debug_level: "info"

# Resource monitoring
monitoring_enable_resource_monitoring: true
monitoring_resource_alert_threshold_cpu: 80
monitoring_resource_alert_threshold_memory: 85
monitoring_resource_alert_threshold_disk: 90

# Service dependencies
monitoring_wait_for_services: true
monitoring_service_start_delay: 10
monitoring_service_start_timeout: 300

# Maintenance mode
monitoring_maintenance_mode: false
monitoring_maintenance_message: "Monitoring stack is under maintenance"

# Native service configuration
monitoring_services_config_dir: "{{ monitoring_base_dir }}/config"
monitoring_services_data_dir: "{{ monitoring_base_dir }}/data"
monitoring_services_log_dir: "{{ monitoring_base_dir }}/logs"

# Binary installation settings
monitoring_temp_dir: "/tmp"
monitoring_install_dir: "/usr/local/bin"

# System service configuration
monitoring_systemd_restart_policy: "on-failure"
monitoring_systemd_restart_delay: "5s"

# File permissions
monitoring_file_mode: "0644"
monitoring_exec_mode: "0755"
monitoring_dir_mode: "0755"

# Logging configuration
monitoring_log_format: "json"
monitoring_log_level: "info"
monitoring_syslog_enabled: true
monitoring_journal_enabled: true

# Network configuration
monitoring_bind_address: "0.0.0.0"
monitoring_enable_ipv6: false

# Monitoring services list (for scripts and automation)
monitoring_services:
  - name: "node_exporter"
    port: 9100
    path: "/metrics"
  - name: "prometheus"
    port: 9090
    path: "/api/v1/status"
  - name: "grafana-server"
    port: 3000
    path: "/api/health"
  - name: "alertmanager"
    port: 9093
    path: "/api/v1/status"

# Archive extraction settings
monitoring_archive_timeout: 300
monitoring_checksum_verify: true

# Update and maintenance
monitoring_config_backup_enabled: true
monitoring_config_backup_dir: "{{ monitoring_backup_dir }}/configs"
