---
dependencies:
  - role: monitoring-common
    when: monitoring_deploy_common | default(true)

  - role: prometheus
    when: monitoring_deploy_prometheus | default(true)
    vars:
      prometheus_retention: "{{ meta_prometheus_retention | default('30d') }}"
      prometheus_scrape_interval: "{{ meta_prometheus_scrape_interval | default('15s') }}"
      prometheus_network_name: "{{ monitoring_global_config.network_name | default('monitoring') }}"
      prometheus_network_external: true

  - role: alertmanager
    when: monitoring_deploy_alertmanager | default(true)
    vars:
      alertmanager_smtp_enabled: "{{ meta_alertmanager_smtp_enabled | default(false) }}"
      alertmanager_slack_enabled: "{{ meta_alertmanager_slack_enabled | default(false) }}"
      alertmanager_network_name: "{{ monitoring_global_config.network_name | default('monitoring') }}"
      alertmanager_network_external: true

  - role: loki
    when: monitoring_deploy_loki | default(true)
    vars:
      loki_retention_period: "{{ meta_loki_retention_period | default('744h') }}"
      loki_network_name: "{{ monitoring_global_config.network_name | default('monitoring') }}"
      loki_network_external: true

  - role: grafana
    when: monitoring_deploy_grafana | default(true)
    vars:
      grafana_admin_user: "{{ meta_grafana_admin_user | default('admin') }}"
      grafana_admin_password: "{{ meta_grafana_admin_password | default('admin123') }}"
      grafana_plugins: "{{ meta_grafana_plugins | default([]) }}"
      grafana_network_name: "{{ monitoring_global_config.network_name | default('monitoring') }}"
      grafana_network_external: true

  - role: cadvisor
    when: monitoring_deploy_cadvisor | default(true)
    vars:
      cadvisor_network_name: "{{ monitoring_global_config.network_name | default('monitoring') }}"
      cadvisor_network_external: true

galaxy_info:
  author: monitoring-team
  description: Meta role for deploying complete monitoring stack
  company: Example Corp
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
  galaxy_tags:
    - monitoring
    - prometheus
    - grafana
    - loki
    - alertmanager
    - observability
    - metrics
    - logs
    - alerts
