---
# Promtail role variables

# Base directory for Promtail
promtail_base_dir: "/opt/monitoring/promtail"

# Promtail service configuration
promtail_port: 9080
promtail_image: "grafana/promtail:latest"

# Loki connection configuration
promtail_loki_url: "http://loki:3100/loki/api/v1/push"
promtail_loki_tenant_id: ""
promtail_loki_batch_wait: "1s"
promtail_loki_batch_size: 1048576  # 1MB

# Server configuration
promtail_server_http_listen_port: 9080
promtail_server_grpc_listen_port: 0
promtail_server_log_level: "info"

# Positions configuration
promtail_positions_file: "/tmp/positions.yaml"
promtail_positions_sync_period: "10s"

# Log paths to collect
promtail_log_paths:
  - /var/log/*.log
  - /var/log/**/*.log

# Docker logs collection
promtail_docker_logs_enabled: true
promtail_docker_logs_path: "/var/lib/docker/containers"

# Additional log sources
promtail_additional_scrape_configs: []

# Default labels to add to all logs
promtail_external_labels:
  host: "{{ ansible_hostname }}"
  environment: "{{ environment | default('production') }}"

# Pipeline stages
promtail_pipeline_stages:
  - regex:
      expression: '(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?)'
  - timestamp:
      source: timestamp
      format: "RFC3339"
      fallback_formats:
        - "2006-01-02T15:04:05.999999999Z07:00"
        - "2006-01-02T15:04:05Z07:00"
        - "2006-01-02T15:04:05.999Z"
        - "2006-01-02T15:04:05"
        - "2006-01-02 15:04:05.999999999 -0700 MST"
        - "2006-01-02 15:04:05"

# Journal scraping (systemd logs)
promtail_journal_enabled: true
promtail_journal_max_age: "12h"
promtail_journal_labels:
  job: systemd-journal

# Syslog receiver configuration
promtail_syslog_enabled: false
promtail_syslog_listen_address: "0.0.0.0:1514"
promtail_syslog_idle_timeout: "60s"
promtail_syslog_label_structured_data: true
promtail_syslog_labels:
  job: syslog

# Target configuration
promtail_target_config_sync_period: "15s"

# Client configuration
promtail_client_backoff_config:
  min_period: "500ms"
  max_period: "5m"
  max_retries: 10

promtail_client_timeout: "10s"

# Rate limiting
promtail_limits_config:
  readline_rate_enabled: true
  readline_rate: 10000
  readline_burst: 10000

# File target configuration
promtail_file_sd_configs: []

# Static configs for additional targets
promtail_static_configs: []

# Relabel configs
promtail_relabel_configs:
  - source_labels: ['__path__']
    regex: '/var/log/(.*)'
    target_label: 'logfile'
    replacement: '$1'

# Network settings
promtail_network_name: "monitoring"
promtail_network_external: true

# Docker specific settings
promtail_container_name: "promtail"
promtail_restart_policy: "unless-stopped"

# Volume mounts
promtail_volumes:
  - ./configs/promtail-config.yml:/etc/promtail/config.yml:ro
  - ./positions:/tmp:rw
  - /var/log:/var/log:ro
  - /var/lib/docker/containers:/var/lib/docker/containers:ro

# Additional volumes (user-defined)
promtail_additional_volumes: []

# Environment variables
promtail_env_vars: {}

# Health check settings
promtail_healthcheck_interval: "30s"
promtail_healthcheck_timeout: "10s"
promtail_healthcheck_retries: 3
promtail_healthcheck_start_period: "10s"

# Log level
promtail_log_level: "info"
promtail_log_format: "logfmt"

# Promtail specific configurations
promtail_tail_from_head: false
promtail_max_label_name_length: 1024
promtail_max_label_value_length: 2048

# Authentication
promtail_basic_auth_username: ""
promtail_basic_auth_password: ""
promtail_bearer_token: ""
promtail_bearer_token_file: ""

# TLS configuration
promtail_tls_enabled: false
promtail_tls_ca_file: ""
promtail_tls_cert_file: ""
promtail_tls_key_file: ""
promtail_tls_server_name: ""
promtail_tls_insecure_skip_verify: false

# Proxy configuration
promtail_proxy_url: ""
promtail_no_proxy: ""

# Extra labels for specific log files
promtail_log_labels: {}
# Example:
# promtail_log_labels:
#   '/var/log/nginx/access.log':
#     service: nginx
#     log_type: access
#   '/var/log/nginx/error.log':
#     service: nginx
#     log_type: error
