---
# Promtail host installation variables

# Promtail version
promtail_version: "2.9.3"

# System architecture mapping
promtail_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "arm"
  armv6l: "arm"

# Download URL
promtail_download_url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-{{ promtail_arch_map[ansible_architecture] }}.zip"

# Installation paths
promtail_bin_path: "/usr/local/bin/promtail"
promtail_config_dir: "/etc/promtail"
promtail_config_file: "{{ promtail_config_dir }}/promtail.yml"
promtail_positions_file: "/var/lib/promtail/positions.yaml"
promtail_data_dir: "/var/lib/promtail"

# Service configuration
promtail_service_name: "promtail"
promtail_user: "promtail"
promtail_group: "promtail"

# Loki server configuration
promtail_loki_url: "http://{{ hostvars[groups['monitoring_servers'][0]]['ansible_host'] }}:3100/loki/api/v1/push"

# HTTP server configuration
promtail_http_listen_port: 9080
promtail_grpc_listen_port: 0

# Log files to scrape
promtail_scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: "{{ inventory_hostname }}"
          __path__: /var/log/*.log

  - job_name: apt
    static_configs:
      - targets:
          - localhost
        labels:
          job: apt
          host: "{{ inventory_hostname }}"
          __path__: /var/log/apt/*.log

  - job_name: journal
    journal:
      json: false
      max_age: 12h
      labels:
        job: systemd-journal
        host: "{{ inventory_hostname }}"
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"

  - job_name: auth-journal
    journal:
      json: false
      max_age: 12h
      labels:
        job: auth
        host: "{{ inventory_hostname }}"
      matches: _SYSTEMD_UNIT=ssh.service
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"

# Pipeline stages for log processing
promtail_pipeline_stages:
  - timestamp:
      source: time
      format: "RFC3339Nano"
      fallback_formats:
        - "RFC3339"
        - "RFC822"
        - "UnixDate"
        - "RubyDate"
        - "RFC822Z"
        - "RFC1123"
        - "RFC1123Z"
        - "RFC3339"
        - "RFC3339Nano"

  - labels:
      stream:

  - output:
      source: output

# Additional labels to add to all logs
promtail_external_labels:
  hostname: "{{ inventory_hostname }}"
  environment: "{{ environment | default('production') }}"

# Resource limits
promtail_memory_limit: "512M"
promtail_cpu_limit: "50%"

# Log rotation
promtail_log_level: "info"
promtail_log_format: "logfmt"

# Security
promtail_cap_add:
  - CAP_DAC_READ_SEARCH # Allows reading files that the user doesn't own

# Systemd service settings
promtail_service_enabled: true
promtail_service_state: started
promtail_restart_on_failure: true
promtail_restart_sec: 5
