---
# Main site playbook - Entry point for all Ansible operations
- import_playbook: playbooks/install-docker.yml
  tags: docker

- import_playbook: playbooks/deploy-monitoring.yml
  tags: monitoring

# Additional playbooks can be added here as the project grows
# - import_playbook: playbooks/security.yml
#   tags: security