---
- name: restart node-exporter
  command: docker compose -p node-exporter -f {{ node_exporter_base_dir }}/docker-compose.yml restart
  args:
    chdir: "{{ node_exporter_base_dir }}"

- name: stop node-exporter
  command: docker compose -p node-exporter -f {{ node_exporter_base_dir }}/docker-compose.yml down
  args:
    chdir: "{{ node_exporter_base_dir }}"

- name: start node-exporter
  command: docker compose -p node-exporter -f {{ node_exporter_base_dir }}/docker-compose.yml up -d
  args:
    chdir: "{{ node_exporter_base_dir }}"
