---
- name: restart promtail
  command: docker compose -p promtail -f {{ promtail_base_dir }}/docker-compose.yml restart
  args:
    chdir: "{{ promtail_base_dir }}"
  when: not ansible_check_mode

- name: stop promtail
  command: docker compose -p promtail -f {{ promtail_base_dir }}/docker-compose.yml down
  args:
    chdir: "{{ promtail_base_dir }}"
  when: not ansible_check_mode

- name: start promtail
  command: docker compose -p promtail -f {{ promtail_base_dir }}/docker-compose.yml up -d
  args:
    chdir: "{{ promtail_base_dir }}"
  when: not ansible_check_mode

- name: reload promtail
  command: docker exec promtail kill -HUP 1
  ignore_errors: yes
