---
# Monitoring Scripts Role Defaults

# Base directories
monitoring_base_dir: /opt/monitoring
monitoring_scripts_dir: "{{ monitoring_base_dir }}/scripts"
monitoring_backup_dir: "{{ monitoring_base_dir }}/backups"

# User configuration
monitoring_user: monitoring
monitoring_create_user: false

# Backup configuration
monitoring_enable_backup: true
monitoring_backup_hour: "2"
monitoring_backup_minute: "0"
monitoring_backup_retention_days: 7

# Health check configuration
monitoring_healthcheck_enabled: true
monitoring_healthcheck_interval: "*/5"

# Script permissions
monitoring_script_owner: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
monitoring_script_group: "{{ monitoring_user if monitoring_create_user else ansible_user }}"
monitoring_script_mode: "0755"

# Services to monitor (used by check-services.sh)
monitoring_services:
  - name: "prometheus"
    port: 9090
    path: "/-/ready"
    service_type: "docker"
  - name: "grafana"
    port: 3000
    path: "/api/health"
    service_type: "docker"
  - name: "loki"
    port: 3100
    path: "/ready"
    service_type: "docker"
  - name: "alertmanager"
    port: 9093
    path: "/-/ready"
    service_type: "docker"
  - name: "cadvisor"
    port: 8080
    path: "/healthz"
    service_type: "docker"
  - name: "node_exporter"
    port: 9100
    path: "/metrics"
    service_type: "systemd"
  - name: "promtail"
    port: 9080
    path: "/targets"
    service_type: "systemd"

# Notification settings for scripts
monitoring_notification_enabled: false
monitoring_notification_email: ""
monitoring_notification_slack_webhook: ""

# Log settings for scripts
monitoring_script_log_dir: "{{ monitoring_base_dir }}/logs"
monitoring_script_log_level: "info"
monitoring_script_log_retention: 30

# Health check thresholds
monitoring_health_cpu_threshold: 80
monitoring_health_memory_threshold: 85
monitoring_health_disk_threshold: 90
monitoring_health_load_threshold: 2.0

# Backup settings
monitoring_backup_compress: true
monitoring_backup_encrypt: false
monitoring_backup_remote_enabled: false
monitoring_backup_remote_host: ""
monitoring_backup_remote_path: ""
monitoring_backup_remote_user: ""

# Script execution settings
monitoring_script_timeout: 300
monitoring_script_max_retries: 3
monitoring_script_retry_delay: 10
